### ISSUE TITLE
Adding/changing commands sends back chat

### ISSUE THREAD

**Issue by jowanw** [cnaude/PurpleIRC#105]
When i try to add a command / change a command it kinda works but it will send ingame irc chat to irc.

http://imgur.com/3HDYD67

**Comment by cnaude** [comment]
What does your bot yml look like? Please use pastebin.

**Comment by jowanw** [comment]
http://pastebin.com/CNrrycHh

**Comment by cnaude** [comment]
That's bizarre. I've seen this happen once before. Would you please turn on debug mode and send me the output when you send a test message? 
/irc debug t
Send test message
/irc debug f

**Comment by jowanw** [comment]
http://pastebin.com/sdf8pqun

The [IRC] thing only happens after i use the command.

**Comment by cnaude** [comment]
I just realized this is for PurpleIRC-spigot. That changes things a bit for my testing...

**Comment by cnaude** [comment]
I was able to successfully replicate the problem.

**Comment by cnaude** [comment]
Fixed in latest dev build: http://h.cnaude.org:8081/job/PurpleIRC-spigot/35/

**Comment by jowanw** [comment]
Sadly i still cant slap from irc :P guess its an errow with commandbook now, 

26.02 18:29:28 [Server] ERROR Error running command: Unhandled exception executing 'slap jowanw' in com.sk89q.bukkit.util.DynamicPluginCommand(slap)

**Comment by cnaude** [comment]
In your command try this:
sender: '%NICK%

**Comment by jowanw** [comment]
Got the same error:

26.02 18:39:11 [Server] ERROR Error running command: Unhandled exception executing 'slap jowanw' in com.sk89q.bukkit.util.DynamicPluginCommand(slap)

slap:
        modes: o
        private: 'false'
        ctcp: 'false'
        game_command: slap %ARGS%
        private_listen: 'true'
        channel_listen: 'true'
        sender: 'NICK'
        perm: ''

**Comment by cnaude** [comment]
What version of CommandBook is that and where did you download it?
Also sender should be %NICK% not just NICK.

**Comment by jowanw** [comment]
using %nick% gave me an error:

26.02 18:37:31 [Server] ERROR Error running command: Unhandled exception executing 'slap %NICK%' in com.sk89q.bukkit.util.DynamicPluginCommand(slap)

Im running CommandBook 2.4:1692-75bb1c8,master

**Comment by cnaude** [comment]
I think I know what's going on.

**Comment by jowanw** [comment]
And what do you think it is?

**Comment by cnaude** [comment]
It's an issue with CommandBook and Spigot. CommandBook is not registering the slap command in a way that I can detect correctly. PurpleIRC sees it as a vanilla command. It tries to use the vanilla command wrapper. I have to figure out a workaround.

**Comment by cnaude** [comment]
Figured it out. Fixed in latest build: http://h.cnaude.org:8081/job/PurpleIRC-spigot/36/

**Comment by jowanw** [comment]
Awesome :)  Now i probably have some config fault since is returning that i dont have permissions. i am op in the irc channel, this is my config atm: 

      slap:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: slap %ARGS%
        private_listen: 'true'
        channel_listen: 'true'
        sender: CONSOLE
        perm: 'o'

i changed sender from NICK to CONSOLE, and that didnt fix it

**Comment by cnaude** [comment]
The perm is option is for game permissions. Change that to '' instead. If you want only ops to run the command then set modes to 'o'.

**Comment by jowanw** [comment]
Mmm, it doesnt seem to be working for me. i tryed both perm: ' ' and 'o' and both give me "You dont have permission"

      slap:
        modes: '*'
        private: 'false'
        ctcp: 'false'
        game_command: slap %ARGS%
        private_listen: 'true'
        channel_listen: 'true'
        sender: CONSOLE
        perm: ''

**Comment by jowanw** [comment]
Changing op-permissions: true in commandbook config seems to fix it, kinda weird since it sends the commands via console.

**Comment by jowanw** [comment]
:/ yesterday it worked for me, and not other ops. now it isnt working at all.. i set perms to op, we are both op in IRC channel:

10:03	jowanw	.slap me
10:03	EvilWhaleBot	I'm sorry 'jowanw' you are not authorized to do that. Type '.help' for a list of commands I might respond to.

**Comment by cnaude** [comment]
That's really odd. Can i see the debug output from that?

**Comment by jowanw** [comment]
Erhm, i think i know why its saying that. someone with the same name has to be online.

27.02 15:16:45 [Server] INFO [DEBUG] [blockingIRCMessage] Message sent to #evilwhale
27.02 15:16:45 [Server] INFO [DEBUG] [blockingIRCMessage] About to send IRC message to #evilwhale
27.02 15:16:45 [Server] INFO [DEBUG] [0]: queueAndSend message detected
27.02 15:16:45 [Server] INFO [DEBUG] Entering aysncIRCMessage
27.02 15:16:45 [Server] INFO [DEBUG] User 'jowanw' mode not okay.
27.02 15:16:45 [Server] INFO [DEBUG] [checkPerm] Player not online: jowanw
27.02 15:16:45 [Server] INFO [DEBUG] Target: #evilwhale
27.02 15:16:45 [Server] INFO [DEBUG] channelListen: true
27.02 15:16:45 [Server] INFO [DEBUG] privateListen: true
27.02 15:16:45 [Server] INFO [DEBUG] .slap
27.02 15:16:45 [Server] INFO [DEBUG] IRC command detected: slap
27.02 15:16:45 [Server] INFO [DEBUG] processMessage: .slap
27.02 15:16:45 [Server] INFO [DEBUG] Shortify: false
27.02 15:16:45 [Server] INFO [DEBUG] Message caught <jowanw>: .slap
27.02 15:16:40 [Server] INFO Debug mode is now true


So if i want to slap as 'jowanw'  the player jowanw has to be online to check perms.

**Comment by cnaude** [comment]
It thinks your mode is not correct. What does that command look like right now?

**Comment by jowanw** [comment]
modes: o
        private: 'false'
        ctcp: 'false'
        game_command: slap %NICK%
        private_listen: 'true'
        channel_listen: 'true'
        sender: CONSOLE
        perm: 'o'

I tried mode 'o', '*', "

**Comment by cnaude** [comment]
Try this:
```yaml
    modes: '*'
    private: 'false'
    ctcp: 'false'
    game_command: slap %NICK%
    private_listen: 'true'
    channel_listen: 'true'
    sender: CONSOLE
    perm: ''
```

**Comment by jowanw** [comment]
This works, but none ops can also slap from irc.

**Comment by cnaude** [comment]
If you only want users in IRC that have ops the ability then use this.

```yaml
    modes: 'o'
    private: 'false'
    ctcp: 'false'
    game_command: slap %NICK%
    private_listen: 'true'
    channel_listen: 'true'
    sender: CONSOLE
    perm: ''
```

**Comment by cnaude** [comment]
I should make the debug output for the permissions a little more obvious. Right now the message is the same or irc and game permissions.

**Comment by jowanw** [comment]
Well it works now :)

**Comment by cnaude** [comment]
Awesome :)

**Comment by jowanw** [comment]
Or im stupid or blind but ... 

15:48	jowanw	.slap RPG_Gev
15:48	EvilWhaleBot	No players matched query.
15:48	jowanw	.list
15:48	EvilWhaleBot	[Minecraft] Online (5/20): iTig3rs, Rika_legotown, RPG_Gev, Viggen2004, xXChrisMCXx
15:48	jowanw	.slap RPG_Gev
15:48	EvilWhaleBot	No players matched query.
15:49	EvilWhaleBot	<Rika_legotown> why
15:49	EvilWhaleBot	<Viggen2004> want marshmallows
15:49	jowanw	.slap RPG_Gev
15:49	EvilWhaleBot	No players matched query.
15:49	EvilWhaleBot	<Rika_legotown> yes
15:50	EvilWhaleBot	<iTig3rs>
15:50	EvilWhaleBot	<Rika_legotown> i like this
15:51	jowanw	.slap Viggen2004
15:51	EvilWhaleBot	No players matched query.

**Comment by jowanw** [comment]
27.02 15:52:49 [Server] INFO [DEBUG] [blockingIRCMessage] Message sent to #evilwhale
27.02 15:52:49 [Server] INFO [DEBUG] [blockingIRCMessage] About to send IRC message to #evilwhale
27.02 15:52:49 [Server] INFO [DEBUG] [0]: queueAndSend message detected
27.02 15:52:49 [Server] INFO [DEBUG] sendMessage: §cNo players matched query.
27.02 15:52:49 [Server] INFO [DEBUG] Dispatching command as IRCCommandSender: slap %NICK%
27.02 15:52:49 [Server] INFO [DEBUG] Is this is a CommandBook command? true
27.02 15:52:49 [Server] INFO [DEBUG] CMD: slap
27.02 15:52:49 [Server] INFO [DEBUG] Adding command to queue: slap %NICK%
27.02 15:52:49 [Server] INFO [DEBUG] GM: "slap %NICK%"
27.02 15:52:49 [Server] INFO [DEBUG] Target: #evilwhale
27.02 15:52:49 [Server] INFO [DEBUG] channelListen: true
27.02 15:52:49 [Server] INFO [DEBUG] privateListen: true
27.02 15:52:49 [Server] INFO [DEBUG] .slap RPG_Gev
27.02 15:52:49 [Server] INFO [DEBUG] IRC command detected: slap
27.02 15:52:49 [Server] INFO [DEBUG] processMessage: .slap RPG_Gev
27.02 15:52:49 [Server] INFO [DEBUG] Shortify: false
27.02 15:52:49 [Server] INFO [DEBUG] Message caught <jowanw>: .slap RPG_Gev
27.02 15:52:40 [Server] INFO Debug mode is now true

**Comment by jowanw** [comment]
Okay, changing %NICK% to %ARGS% fixes it!? They should be the same.

**Comment by cnaude** [comment]
Those two tokens are different. The %NICK% token contains the name of the IRC user submitting the command. The %ARGS% contains all of the arguments sent to the command.
